Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import PyPDF2
from pathlib import Path

def PDFmerge(pdfs, output):
        
    pdf_write_object = PyPDF2.PdfFileWriter()
    
    for pdf in pdfs:
        pdf_read_object = PyPDF2.PdfFileReader(pdf)
        for page in range(pdf_read_object.numPages):
            pdf_write_object.addPage(pdf_read_object.getPage(page))

    final_file_object = open(output, 'wb')
    pdf_write_object.write(final_file_object)
    final_file_object.close() 
        
def main(input_folder, output_name):

    pathlist = Path(input_folder).glob('*.pdf')

    pdfs = [str(i) for i in pathlist]
    print(pdfs)
    PDFmerge(pdfs, output_name)
    
    
if __name__ == '__main__':
    main(input_folder='pdfs', output_name='pdfs/pdf_filename.pdf')

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-1-0c580e5896f4>[0m in [0;36m<module>[0;34m[0m
[1;32m     25[0m [0;34m[0m[0m
[1;32m     26[0m [0;32mif[0m [0m__name__[0m [0;34m==[0m [0;34m'__main__'[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 27[0;31m     [0mmain[0m[0;34m([0m[0minput_folder[0m[0;34m=[0m[0;34m'pdfs'[0m[0;34m,[0m [0moutput_name[0m[0;34m=[0m[0;34m'pdfs/pdf_filename.pdf'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m<ipython-input-1-0c580e5896f4>[0m in [0;36mmain[0;34m(input_folder, output_name)[0m
[1;32m     21[0m     [0mpdfs[0m [0;34m=[0m [0;34m[[0m[0mstr[0m[0;34m([0m[0mi[0m[0;34m)[0m [0;32mfor[0m [0mi[0m [0;32min[0m [0mpathlist[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m     22[0m     [0mprint[0m[0;34m([0m[0mpdfs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 23[0;31m     [0mPDFmerge[0m[0;34m([0m[0mpdfs[0m[0;34m,[0m [0moutput_name[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     24[0m [0;34m[0m[0m
[1;32m     25[0m [0;34m[0m[0m

[0;32m<ipython-input-1-0c580e5896f4>[0m in [0;36mPDFmerge[0;34m(pdfs, output)[0m
[1;32m     11[0m             [0mpdf_write_object[0m[0;34m.[0m[0maddPage[0m[0;34m([0m[0mpdf_read_object[0m[0;34m.[0m[0mgetPage[0m[0;34m([0m[0mpage[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     12[0m [0;34m[0m[0m
[0;32m---> 13[0;31m     [0mfinal_file_object[0m [0;34m=[0m [0mopen[0m[0;34m([0m[0moutput[0m[0;34m,[0m [0;34m'wb'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     14[0m     [0mpdf_write_object[0m[0;34m.[0m[0mwrite[0m[0;34m([0m[0mfinal_file_object[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     15[0m     [0mfinal_file_object[0m[0;34m.[0m[0mclose[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'pdfs/pdf_filename.pdf'
FileNotFoundError: [Errno 2] No such file or directory: 'pdfs/pdf_filename.pdf'

