Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# The "describe" method didn't seem to work. Let's try to plot 'price' using a boxplot and histogram. Why doesn't this work?
df.boxplot(column=['price'])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m<ipython-input-5-232150201d49>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# The "describe" method didn't seem to work. Let's try to plot 'price' using a boxplot and histogram. Why doesn't this work?[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mdf[0m[0;34m.[0m[0mboxplot[0m[0;34m([0m[0mcolumn[0m[0;34m=[0m[0;34m[[0m[0;34m'price'[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/opt/anaconda3/lib/python3.7/site-packages/pandas/plotting/_core.py[0m in [0;36mboxplot_frame[0;34m(self, column, by, ax, fontsize, rot, grid, figsize, layout, return_type, **kwds)[0m
[1;32m    418[0m         [0mlayout[0m[0;34m=[0m[0mlayout[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    419[0m         [0mreturn_type[0m[0;34m=[0m[0mreturn_type[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 420[0;31m         [0;34m**[0m[0mkwds[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    421[0m     )
[1;32m    422[0m [0;34m[0m[0m

[0;32m/opt/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/boxplot.py[0m in [0;36mboxplot_frame[0;34m(self, column, by, ax, fontsize, rot, grid, figsize, layout, return_type, **kwds)[0m
[1;32m    353[0m         [0mlayout[0m[0;34m=[0m[0mlayout[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    354[0m         [0mreturn_type[0m[0;34m=[0m[0mreturn_type[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 355[0;31m         [0;34m**[0m[0mkwds[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    356[0m     )
[1;32m    357[0m     [0mplt[0m[0;34m.[0m[0mdraw_if_interactive[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/boxplot.py[0m in [0;36mboxplot[0;34m(data, column, by, ax, fontsize, rot, grid, figsize, layout, return_type, **kwds)[0m
[1;32m    318[0m             [0mcolumns[0m [0;34m=[0m [0mdata[0m[0;34m.[0m[0mcolumns[0m[0;34m[0m[0;34m[0m[0m
[1;32m    319[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 320[0;31m             [0mdata[0m [0;34m=[0m [0mdata[0m[0;34m[[0m[0mcolumns[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    321[0m [0;34m[0m[0m
[1;32m    322[0m         [0mresult[0m [0;34m=[0m [0mplot_group[0m[0;34m([0m[0mcolumns[0m[0;34m,[0m [0mdata[0m[0;34m.[0m[0mvalues[0m[0;34m.[0m[0mT[0m[0;34m,[0m [0max[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py[0m in [0;36m__getitem__[0;34m(self, key)[0m
[1;32m   2984[0m             [0;32mif[0m [0mis_iterator[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2985[0m                 [0mkey[0m [0;34m=[0m [0mlist[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2986[0;31m             [0mindexer[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mloc[0m[0;34m.[0m[0m_convert_to_indexer[0m[0;34m([0m[0mkey[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0;36m1[0m[0;34m,[0m [0mraise_missing[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   2987[0m [0;34m[0m[0m
[1;32m   2988[0m         [0;31m# take() does not accept boolean indexers[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py[0m in [0;36m_convert_to_indexer[0;34m(self, obj, axis, is_setter, raise_missing)[0m
[1;32m   1283[0m                 [0;31m# When setting, missing keys are not allowed, even with .loc:[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1284[0m                 [0mkwargs[0m [0;34m=[0m [0;34m{[0m[0;34m"raise_missing"[0m[0;34m:[0m [0;32mTrue[0m [0;32mif[0m [0mis_setter[0m [0;32melse[0m [0mraise_missing[0m[0;34m}[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1285[0;31m                 [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_get_listlike_indexer[0m[0;34m([0m[0mobj[0m[0;34m,[0m [0maxis[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[[0m[0;36m1[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1286[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1287[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py[0m in [0;36m_get_listlike_indexer[0;34m(self, key, axis, raise_missing)[0m
[1;32m   1090[0m [0;34m[0m[0m
[1;32m   1091[0m         self._validate_read_indexer(
[0;32m-> 1092[0;31m             [0mkeyarr[0m[0;34m,[0m [0mindexer[0m[0;34m,[0m [0mo[0m[0;34m.[0m[0m_get_axis_number[0m[0;34m([0m[0maxis[0m[0;34m)[0m[0;34m,[0m [0mraise_missing[0m[0;34m=[0m[0mraise_missing[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1093[0m         )
[1;32m   1094[0m         [0;32mreturn[0m [0mkeyarr[0m[0;34m,[0m [0mindexer[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py[0m in [0;36m_validate_read_indexer[0;34m(self, key, indexer, axis, raise_missing)[0m
[1;32m   1175[0m                 raise KeyError(
[1;32m   1176[0m                     "None of [{key}] are in the [{axis}]".format(
[0;32m-> 1177[0;31m                         [0mkey[0m[0;34m=[0m[0mkey[0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0mself[0m[0;34m.[0m[0mobj[0m[0;34m.[0m[0m_get_axis_name[0m[0;34m([0m[0maxis[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1178[0m                     )
[1;32m   1179[0m                 )

[0;31mKeyError[0m: "None of [Index(['price'], dtype='object')] are in the [columns]"
KeyError: "None of [Index(['price'], dtype='object')] are in the [columns]"

